language: python
node_js:
  - '3.7-stretch'

# S: Build Lifecycle
install:
  - pip install jupyter-book
#  - pip install -r requirements.txt
#  - npm install gitbook-cli
#  - jupyter-book build .

script:
  - make clean
  - jupyter-book upgrade /home/travis/build/${GH_REF}
  - make book

deploy:
  local_dir: _build
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: ${test_token}  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: master

branchs:
  only:
    master